### PR TITLE
Issue1: fix next and previous actions

### LINKED ISSUE #1: Fix nex prev problem

### PR DESCRIPTION
**Pull request by kh0ma**

### CODE REVIEW

File: main.js [hunk 1]
```diff
@@ -1,41 +1,44 @@
...
-	slides[index].classList.add('active');
-}
+function nextSlide() {
 
-function prevSlide(){
-	slides[index].classList.remove('active');
-	index = (index - 1 + slides.length) % slides.length;
-	slides[index].classList.add('active');
-}
+    slides[index].classList.remove('active');
```
Comment (kh0ma) [inline main.js:9]: LEts do a different way. @anatoliy-stepanchenko
